stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - data/text/ 
    params: 
    - prepare
    - experiment
    outs:
     - data/prepared 

  inference:
    cmd: torchrun src/inference.py
    deps:
    - src/inference.py
    - data/prepared/
    params:
    - inference
    - experiment
    outs:
    - data/inference

  projection:
    cmd: python src/projection.py
    deps:
    - src/projection.py
    - data/inference/
    params:
    - projection
    outs:
    - data/projected
    - models/projection

  detection:
    cmd: python src/detection.py
    deps:
    - src/detection.py
    - data/projected/
    params:
    - detection
    outs:
    - data/detection
    - models/detection

  evaluation:
    cmd: python src/evaluation.py
    deps:
    - src/evaluation.py
    - data/projected/
    - models/detection
    params:
    - evaluation
    outs:
    - eval