#######################################
# This is the EXTRACTION DVC pipeline #
#######################################

stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    - data/text/ 
    - prompts.yaml
    params: 
    - prepare
    - experiment.data
    outs:
     - data/prepared 

  inference:
    cmd: torchrun src/inference.py
    deps:
    - src/inference.py
    - data/prepared/
    params:
    - inference
    - experiment.data
    outs:
    - data/inference

  projection:
    cmd: python src/projection.py
    deps:
    - src/projection.py
    - data/inference/
    params:
    - projection
    - experiment.split
    outs:
    - data/projected
    - models/projection

  detection:
    cmd: python src/detection.py
    deps:
    - src/detection.py
    - data/projected/
    params:
    - detection
    - experiment.split
    outs:
    - data/detection
    - models/detection

  evaluation:
    cmd: python src/evaluation.py
    deps:
    - src/evaluation.py
    - data/projected/
    - models/detection
    params:
    - evaluation
    - experiment.split
    outs:
    - eval