stages:
  prepare:
    cmd: python src/prepare.py english_word celebrity
    deps:
    - src/prepare.py
    - data/text/english_word_fake 
    - data/text/english_word_real 
    - data/text/celebrity_fake
    - data/text/celebrity_real 
    params: 
    - prepare.seed
    outs:
     - data/prepared 

  inference:
    cmd: torchrun src/inference.py english_word celebrity
    deps:
    - src/inference.py
    - data/prepared/english_word.pkl
    - data/prepared/celebrity.pkl
    params:
    - inference.seed
    outs:
    - data/inference

  projection:
    cmd: python src/projection.py english_word celebrity
    deps:
    - src/projection.py
    - data/inference/english_word.pkl
    - data/inference/celebrity.pkl
    params:
    - projection.seed
    outs:
    - data/projected
    - models/projection

  detection:
    cmd: python src/detection.py english_word celebrity
    deps:
    - src/detection.py
    - data/projected/english_word.pkl
    - data/projected/celebrity.pkl
    params:
    - detection.seed
    outs:
    - data/detection
    - models/detection

  evaluation:
    cmd: python src/evaluation.py english_word celebrity
    deps:
    - src/evaluation.py
    - data/projected/english_word.pkl
    - data/projected/celebrity.pkl
    - models/detection
    params:
    - evaluation.seed
    outs:
    - data/evaluation