#####################################
# This is the STEERING DVC pipeline #
#####################################

# params:
#   - steering_dvc/params.yaml


stages:
  steering:
    cmd: torchrun ../src/steering_inference.py
    deps:
    - ../src/steering_inference.py
    - ../src/datas.py
    - ../data/features
    - prompts.yaml
    params:
      - steering
      - prepare
    outs:
     - ../data/steered

  evaluation:
    cmd: torchrun ../src/sentence_similarity.py
    deps:
    - ../src/sentence_similarity.py
    - ../data/steered
    - expected_outputs.yaml
    params:
      - evaluation
    outs:
    - ../data/steered_evaluation

  compile:
    cmd: python ../src/compile_results.py
    deps:
    - ../src/compile_results.py
    - ../data/steered_evaluation 
    params:
      - compile
    outs:
    - ../data/compiled_results