# [ Data ]
prepare:
  seed: 1
  text_data_folder: "../data/text"
  prepared_data_folder: "../data/prepared"
  output_file_name: "inference"
  prompt_file: "prompts.yaml"


# [ Steering Inference ]
steering:
  # Data
  evaluation_set: [
    "protein",
    "celebrity",
    "airport",
    "medical",
    "english_word",
    "culture",
    "legal",
    "french_word",
  ]
  output_folder: "../data/steered"
  experiment_label_name: "Qwen2.5-7B-Instruct_all_SPCA_neg80.50.10.0" #"wreal_mainAnchors7.6.4.3.1_clean_ly14" #"protein" #"PCA_softclip1000" #"real_act_mean_more" #"SparsePCA02_more" #"SparsePCA02"
  verbose: True
  seed: 1

  # Model Info
  model_name: "Qwen2.5-7B-Instruct"
  torch_dtype: "torch.bfloat16"
  model_path: "../models/Meta-Llama-3-8B-Instruct/"
  tokenizer_path: "../models/Meta-Llama-3-8B-Instruct/tokenizer.model"
  temperature: 0.5
  top_p: 0.9
  max_seq_len: 256 #512
  max_batch_size: 8
  
  # Vector Info
  steeve_type: "proj_mean_inv" #"proj_mean_inv" # act_mean   # proj_mean_inv #raw_direction
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_english_word_french_word_celebrity_airport_medical_protein_culture_legal_vectors.pkl"
  vector_path: "../data/projected/Qwen2.5-7B-Instruct_SparsePCAProjectionModel_trained_on_celebrity_vectors_celeb2others.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_english_word_french_word_celebrity_airport_medical_protein_culture_legal_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_english_word_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_airport_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_pokemon_idk_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_pokemon_bluff_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_celebrity_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_english_word_vectors.pkl"
  # vector_path: "../data/projected/PCAProjectionModel_trained_on_english_word_vectors.pkl"
  # vector_path: "../data/projected/SparsePCAProjectionModel_trained_on_celebrity_vectors.pkl"
  layers: [19]
  alpha: [1] #[-8, -5, -1, 1, 5, 8]
  beta: [-70, -60, -40, -30, -20, 20, 30, 40, 60, 70] #[-80, -50, -10, 0, 10, 50, 80] 
  clip_value: [0]
  clip_type: "soft_clip"
  act_space_norm: True
  norm_before_clip: True
  on_prompt: True
  slerp: False
  one_time_steer: False
  manipulation_decay: 1.0

# [ Evaluation of Outputs]
evaluation:
  expected_outputs_path: "expected_outputs.yaml"
  few_shot_path: "few_shot.yaml"
  similarity_decision_threshold: 0.1
  seed: 1
  output_folder: "../data/steered_evaluation"
  verbose: True


# [ Compile Results]
compile:
  seed: 0
  compilation_prefix: "Qwen2.5-7b-Instruct" #"disruption_inspect_2" #"Redo SPCA english" #"robustness all" #"robustness_en2med"
  compilation_folder: "../data/compiled"
  palette: [
    "#f8c091",  #// Pastel orange (from #ee6a00)
    "#d0f2ea",  #// Lighter pastel teal (from #a1e8d9)
    "#b5ad98",  #// Pastel taupe (from #695d46)
    "#99d5b9",  #// Pastel green (from #009667)
    "#e7c7e9",  #// Pastel lavender (from #cd92d7)
    "#d6cfb8",  #// Pastel beige (from #b3a77d)
    "#f5ffb3",  #// Pastel yellow (from #eeff41)
    "#ffbd91",  #// Pastel coral (from #ef6c00)
    "#a9ded8",   #// Pastel aqua (from #4db6ac)
  ]
