# [ Data ]
prepare:
  seed: 1
  text_data_folder: "../data/text"
  prepared_data_folder: "../data/prepared"
  output_file_name: "inference"
  prompt_file: "prompts.yaml"


# [ Steering Inference ]
steering:
  # Data
  evaluation_set: ["poem"]
  output_folder: "../data/steered"
  experiment_label_name: "poem2"
  verbose: True
  seed: 1

  # Model Info
  model_path: "../models/Meta-Llama-3-8B-Instruct/"
  tokenizer_path: "../models/Meta-Llama-3-8B-Instruct/tokenizer.model"
  temperature: 0.5
  top_p: 0.9
  max_seq_len: 2048
  max_batch_size: 8
  
  # Vector Info
  steeve_type: "raw_direction" # act_mean   # proj_mean_inv
  vector_path: "../data/features/PCA_handmade_length_layer3.pkl"
  layers: [18]
  alpha: [1] #[-8, -5, -1, 1, 5, 8]
  beta: [-9, 9]
  clip_value: [0]
  clip_type: "soft_clip"
  act_space_norm: True
  norm_before_clip: True
  on_prompt: True
  one_time_steer: False
  manipulation_decay: 1.0

# [ Evaluation of Outputs]
evaluation:
  expected_outputs_path: "expected_outputs.yaml"
  few_shot_path: "few_shot.yaml"
  similarity_decision_threshold: 0.1
  seed: 1
  output_folder: "../data/steered_evaluation"
  verbose: True


# [ Compile Results]
compile:
  seed: 1
  compilation_prefix: "length_test"
  compilation_folder: "../data/compiled"
  palette: [
    "#ee6a00",
    "#eeff41",
    "#009667",
    "#cd92d7",
    "#b3a77d",
    "#a1e8d9"
  ]
