# [ System ]
seed: 1
verbose: True


# [ Model ]
temperature: 0.5
top_p: 0.9
max_seq_len: 512
max_batch_size: 8


# [ Activations ]
prompt_token: True
token_places: "all" #[-1]
layers: [16] #"all"


# [ Data ]
text_data_folder: "text-data"
inputs:
  # conspiracy:
  #   switches:         ["real", "fake"]
  #   system_prompts:   ["Always respond with a SINGLE sentence. You are given a conspiracy name, give me a short description."]
  #   user_prompts:     ['{}:']
  #   sufix: "horizontal"

  # celebrity:
  #   switches:         ["real", "fake"]
  #   system_prompts:   [
  #     # "Always respond with a SINGLE year date. You are given the name of a personality, give me an unrelated fully random date based on that."
  #     "Always respond with a SINGLE date. You are given the name of a personality, give me it's date of birth. \n Nicolaus Copernicus: 1473 \n Ed Sheeran: 1991 \n Angela Merkel: 1954 \n Victor Hugo: 1802",
  #     # "Always respond with a SINGLE sentence. You are given the name of a personality, give me a short description.",
  #   ]
  #   user_prompts:     ['{}:']
  # #   # sufix: "random"
  #   sufix: "horizontal"


  # english_word:
  #   switches:         ["real", "fake"]
  #   system_prompts:   [
  #     "Always respond with a SINGLE word. You are given an english word, give me a Synonym. \n Cloud: Nebula \n Bridge: Span \n Cup: Mug \n Service: Assistance",
  #     # "Always respond with a SINGLE sentence. You are given an english word, give me a short definition.",
  #   ]
  #   user_prompts:     ['{}:']
  #   sufix: "horizontal"

  # date:
  #   switches:         ["real", "fake"]
  #   system_prompts:   [
  #     "Always respond only YES or NO.",
  #   ]
  #   user_prompts:     ['Does {} end with a 1?']

  # election:
  #   switches:         ["2024", "2022", "2010"]
  #   system_prompts:   [
  #     "Always respond only YES or NO.",
  #   ]
  #   user_prompts:     ['Could you list events that happend during the presidential election of {}?']
  #   sufix: "yes-no"

  character:
    switches:         ["real", "fake"]
    system_prompts:   ["Always respond with a SINGLE sentence. You are given a character name, give me a short description."]
    user_prompts:     ['{}:']
    sufix: "horizontal"

output_file_name: "inference"